/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
     
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import controller.AppointmentController;
import controller.UsuarioController;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.Appointment;
import model.Usuario;

/**
 *
 * @author Anderson Cafurica
 */
public class TelaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuario
     */
    private Usuario usuarioLogado;
    public TelaUsuario() {
        initComponents();
        UsuarioController usuarioController = new UsuarioController();
        this.usuarioLogado = usuarioController.getUsuarioLogado();
        btnVer.setEnabled(false);
        btnEditar.setEnabled(false);
        btnApagar.setEnabled(false);

        // Se não estiver logado, feche a tela
        if (this.usuarioLogado == null) {
            JOptionPane.showMessageDialog(null, 
                "Usuário não autenticado. Faça login novamente.", 
                "Erro de Autenticação", 
                JOptionPane.ERROR_MESSAGE);
            dispose();
            new Login().setVisible(true);
        }
    }
    
    public void configurarFoto(){
        lbFoto.setBorder(BorderFactory.createEtchedBorder());
        if (usuarioLogado.getPicture() != null){
            try {
                ImageIcon imageIcon = new ImageIcon(usuarioLogado.getPicture()
                );
                Image image = imageIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                lbFoto.setIcon(new ImageIcon(image));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, 
                    "Erro ao Carregar a imagem: "  + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();
        btnMarcar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsulta = new javax.swing.JTable();
        cbTipoConsulta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbPro = new javax.swing.JComboBox<>();
        txtData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        txtSearh = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        lbFoto = new javax.swing.JLabel();
        btnPicture = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(730, 604));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btn_exit.setText("Fechar");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btnMarcar.setText("Marcar Consulta");
        btnMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarActionPerformed(evt);
            }
        });

        btnVer.setText("Ver Consultas");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar Consultas");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnApagar.setText("Apagar Consulta");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        tbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "Dr/Dra", "Tipo de Consulta:", "Data da Consulta:", "Observações:", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbConsulta);

        cbTipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Dentista", "Oftamologia", "Análise", "Outras" }));

        jLabel1.setText("Tipo de Consulta:");

        jLabel2.setText("Profissional:");

        cbPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Raúl", "Dra. Carla", "Dra. Paula", "Dr. Antonio" }));
        cbPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProActionPerformed(evt);
            }
        });

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        jLabel3.setText("Data da Consulta(dd/mm/aaaa HH:MM):");

        jLabel4.setText("Observações:");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRelatorio.setText("Imprimir Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        btnPicture.setText("Add Fotografia");
        btnPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPictureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMarcar)
                        .addGap(82, 82, 82)
                        .addComponent(btnVer)
                        .addGap(57, 57, 57)
                        .addComponent(btnEditar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearh, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_exit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(499, 499, 499)
                        .addComponent(btnApagar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPicture)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_exit)
                    .addComponent(btnSearch))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnPicture)
                                        .addGap(11, 11, 11)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cbPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRelatorio))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarcar)
                    .addComponent(btnVer)
                    .addComponent(btnEditar)
                    .addComponent(btnApagar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbConsultaMouseClicked
        int selectedRow = tbConsulta.getSelectedRow();

        if(selectedRow >= 0){
            btnApagar.setEnabled(true);
            btnEditar.setEnabled(true);
            
            txtData.setText(tbConsulta.getValueAt(selectedRow, 3).toString());
            txtObs.setText(tbConsulta.getValueAt(selectedRow, 4).toString());
        }
    }//GEN-LAST:event_tbConsultaMouseClicked

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        int selectedRow = tbConsulta.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, 
                "Selecione uma consulta para apagar.", 
                "Erro", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(null, 
            "Tem certeza que deseja apagar esta consulta?", 
            "Confirmar Exclusão", 
            JOptionPane.YES_NO_OPTION);

        if (confirmar == JOptionPane.YES_OPTION) {
            try {
                int consultaId = Integer.parseInt(tbConsulta.getValueAt(selectedRow, 5).toString());

                AppointmentController consultaController = new AppointmentController();
                boolean excluido = consultaController.excluirConsulta(consultaId);

                if (excluido) {
                    btnVerActionPerformed(evt);

                    JOptionPane.showMessageDialog(null, 
                        "Consulta apagada com sucesso!", 
                        "Sucesso", 
                        JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, 
                        "Não foi possível apagar a consulta.", 
                        "Erro", 
                        JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, 
                    "Erro ao apagar consulta: " + e.getMessage(), 
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int selectedRow = tbConsulta.getSelectedRow();
    
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, 
                "Selecione uma consulta para editar.", 
                "Erro", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String dataAtual = tbConsulta.getValueAt(selectedRow, 3).toString();
            String tipoConsultaAtual = tbConsulta.getValueAt(selectedRow, 2).toString();
            String obsAtual = tbConsulta.getValueAt(selectedRow, 4).toString();

            String novaData = JOptionPane.showInputDialog(null, 
                "Digite a nova data (dd/mm/aaaa HH:mm):", 
                dataAtual);

            String novoTipo = (String) JOptionPane.showInputDialog(null, 
                "Selecione o novo tipo de consulta:", 
                "Editar Consulta", 
                JOptionPane.QUESTION_MESSAGE, 
                null, 
                new String[]{"Geral", "Dentista", "Oftamologia", "Análise", "Outras"}, 
                tipoConsultaAtual);

            String novaObs = JOptionPane.showInputDialog(null, 
                "Digite novas observações:", 
                obsAtual);

            if (novaData == null || novoTipo == null || novaObs == null) {
                return;
            }

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            LocalDateTime novaDataHora = LocalDateTime.parse(novaData, formatter);

            int consultaId = Integer.parseInt(tbConsulta.getValueAt(selectedRow, 5).toString());

            AppointmentController consultaController = new AppointmentController();
            consultaController.editarConsulta(consultaId, novaDataHora, novoTipo, novaObs);

            btnVerActionPerformed(evt);

            JOptionPane.showMessageDialog(null, 
                "Consulta editada com sucesso!", 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
                "Erro ao editar consulta: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
         try {
            DefaultTableModel model = (DefaultTableModel) tbConsulta.getModel();
            model.setRowCount(0);

            AppointmentController consultaController = new AppointmentController();

            List<Appointment> consultas = consultaController.listarConsultas(usuarioLogado.getId());

            for (Appointment consulta : consultas) {
                String profissional = "";
                switch(consulta.getProfissionalId()) {
                    case 1: profissional = "Dr. Raúl"; break;
                    case 2: profissional = "Dra. Carla"; break;
                    case 3: profissional = "Dra. Paula"; break;
                    case 4: profissional = "Dr. Antonio"; break;
                }

                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
                String dataFormatada = consulta.getDataHora().format(formatter);

                model.addRow(new Object[]{
                    usuarioLogado.getNome(), 
                    profissional, 
                    consulta.getTipoConsulta(), 
                    dataFormatada, 
                    consulta.getObservacao(),
                    consulta.getId()
                });
            }

            if (consultas.isEmpty()) {
                JOptionPane.showMessageDialog(null, 
                    "Você não tem consultas marcadas.", 
                    "Consultas", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
                "Erro ao listar consultas: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarActionPerformed
        try {
            UsuarioController usuario = new UsuarioController();
            if (usuarioLogado == null) {
                JOptionPane.showMessageDialog(null, 
                    "Usuário não está logado. Por favor, faça login primeiro.", 
                    "Erro de Autenticação", 
                    JOptionPane.ERROR_MESSAGE);
            return;
             }

            String profissional = (String) cbPro.getSelectedItem();
            String tipoConsulta = (String) cbTipoConsulta.getSelectedItem();
            String dataHoraStr = txtData.getText().trim();
            String obs = txtObs.getText().trim();

            if (profissional == null || profissional.isEmpty()) {
                JOptionPane.showMessageDialog(null, 
                    "Por favor, selecione um profissional.", 
                    "Campos Obrigatórios", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (tipoConsulta == null || tipoConsulta.isEmpty()) {
                JOptionPane.showMessageDialog(null, 
                    "Por favor, selecione o tipo de consulta.", 
                    "Campos Obrigatórios", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (dataHoraStr.isEmpty()) {
                JOptionPane.showMessageDialog(null, 
                    "Por favor, insira a data e hora da consulta.", 
                    "Campos Obrigatórios", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            DateTimeFormatter formato;
            LocalDateTime dataHora;
            try {
                formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
                dataHora = LocalDateTime.parse(dataHoraStr, formato);
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(null, 
                    "Formato de data inválido. Use o formato dd/MM/yyyy HH:mm", 
                    "Erro de Formato", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (dataHora.isBefore(LocalDateTime.now())) {
                JOptionPane.showMessageDialog(null, 
                    "Não é possível marcar consultas para datas passadas.", 
                    "Data Inválida", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            int profissionalId;
            switch (profissional) {
                case "Dr. Raúl": 
                    profissionalId = 1; 
                    break;
                case "Dra. Carla": 
                    profissionalId = 2; 
                    break;
                case "Dra. Paula": 
                    profissionalId = 3; 
                    break;
                case "Dr. Antonio": 
                    profissionalId = 4; 
                    break;
                default:
                    throw new IllegalArgumentException("Profissional não reconhecido");
            }

            AppointmentController consulta = new AppointmentController();
            Appointment novaConsulta = consulta.marcarConsulta(
                usuarioLogado.getId(), 
                profissionalId, 
                dataHora, 
                tipoConsulta, 
                obs
            );

            btnVer.setEnabled(true);
            txtData.setText("");
            txtObs.setText("");

            JOptionPane.showMessageDialog(null,
                "Consulta Marcada Com Sucesso!",
                "Sucesso na Marcação",
                JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                "Erro ao Marcar Consulta: " + e.getMessage(),
                "Erro na Marcação",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMarcarActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void cbProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        UsuarioController usuarioController = new UsuarioController();
        usuarioController.logout();
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String termoPesquisa = txtSearh.getText().trim();
    
        if (termoPesquisa.isEmpty()) {
            btnVerActionPerformed(evt);
            return;
        }

        try {
            DefaultTableModel model = (DefaultTableModel) tbConsulta.getModel();
            model.setRowCount(0);

            AppointmentController consultaController = new AppointmentController();
            List<Appointment> consultas = consultaController.pesquisarConsultas(
                usuarioLogado.getId(), 
                termoPesquisa
            );

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

            for (Appointment consulta : consultas) {
                String profissional = "";
                switch(consulta.getProfissionalId()) {
                    case 1: profissional = "Dr. Raúl"; break;
                    case 2: profissional = "Dra. Carla"; break;
                    case 3: profissional = "Dra. Paula"; break;
                    case 4: profissional = "Dr. Antonio"; break;
                }

                model.addRow(new Object[]{
                    usuarioLogado.getNome(),
                    profissional,
                    consulta.getTipoConsulta(),
                    consulta.getDataHora().format(formatter),
                    consulta.getObservacao(),
                    consulta.getId()
                });
            }

            if (consultas.isEmpty()) {
                JOptionPane.showMessageDialog(null,
                    "Nenhuma consulta encontrada com o termo: " + termoPesquisa,
                    "Pesquisa",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                "Erro ao pesquisar consultas: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPictureActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Imagens", 
                "jpg", "jpeg", "png", "gif"));
        
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            try {
                File file = fileChooser.getSelectedFile();
                byte[] picture = Files. readAllBytes(file.toPath());
                
                UsuarioController usuarioController = new UsuarioController();
                usuarioController.atualizarFoto(usuarioLogado.getId(), picture);
                
                usuarioLogado.setPicture(picture);
                configurarFoto();
                
                JOptionPane.showMessageDialog(this, 
                        "Foto atualizada com sucesso!",
                        "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE);                        
            } catch (IOException e){
                JOptionPane.showMessageDialog(null, 
                        "Erro ao carregar a foto: "+e.getMessage(),
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnPictureActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new FileNameExtensionFilter("PDF Files", "pdf"));
            fileChooser.setSelectedFile(new File("relatorio_consultas.pdf"));

            if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                if (!file.getName().toLowerCase().endsWith(".pdf")) {
                    file = new File(file.getAbsolutePath() + ".pdf");
                }

                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream(file));
                document.open();

                // Adiciona título
                Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
                Paragraph title = new Paragraph("Relatório de Consultas", titleFont);
                title.setAlignment(Element.ALIGN_CENTER);
                document.add(title);
                document.add(new Paragraph("\n"));

                // Cria tabela
                PdfPTable table = new PdfPTable(5); // 5 colunas
                table.setWidthPercentage(100);

                // Adiciona cabeçalhos
                table.addCell("Paciente");
                table.addCell("Profissional");
                table.addCell("Tipo");
                table.addCell("Data/Hora");
                table.addCell("Observações");

                // Adiciona dados
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
                for (int i = 0; i < tbConsulta.getRowCount(); i++) {
                    for (int j = 0; j < 5; j++) { // Primeiras 5 colunas (exclui o ID)
                        table.addCell(tbConsulta.getValueAt(i, j).toString());
                    }
                }

                document.add(table);
                document.close();

                JOptionPane.showMessageDialog(this,
                    "Relatório gerado com sucesso!\nSalvo em: " + file.getAbsolutePath(),
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Erro ao gerar relatório: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMarcar;
    private javax.swing.JButton btnPicture;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton btn_exit;
    private javax.swing.JComboBox<String> cbPro;
    private javax.swing.JComboBox<String> cbTipoConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JTable tbConsulta;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtSearh;
    // End of variables declaration//GEN-END:variables
}
